version: "3"

services:
  db:
    image: "mongo:4.2"
    restart: always
    volumes:
      - "/data/db:/mongodata"
    env_file:
      - '.env'
    ports:
      - "27017:27017"
    networks: 
      - back-tier
  
  service:
    build: ./node
    volumes:
      - ./node:/app
    command: node index.js
    networks: 
      - back-tier
    env_file: 
      - '.env'

networks:
  back-tier: