version: "3"

services:
  service:
    build: ./node
    volumes:
      - ./tweetCatcher:/app
    command: node index.js
    ports:
      - 3000:3000
    networks: 
      - back-tier
    env_file: 
      - '.env'

networks:
  back-tier: